spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  application:
    name: movie-service
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5002/db_movie
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include:*

keycloak:
  auth-server-url: http://localhost:5555/auth/
  realm: movie-rating
  public-client: false
  resource: app-service
  principal-attribute: preferred_username
  autodetect-bearer-only: true
